AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.1
  Exclude:
    - 'Rakefile'

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 250

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Performance/FixedSize:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Exclude:
    - 'config/routes.rb'
    - 'lib/foreman_ipxe/engine.rb'
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
